### ISSUE TITLE
collections.abc import doesnt exist in python 2

### ISSUE THREAD

**Issue by techalchemy** [sarugaku/mork#4]
Need to use `collections.Set` instead of `collections.abc.Set`

**Comment by techalchemy** [comment]
... maybe this time i will put this on the right project

**Comment by uranusjr** [comment]
OTOH `collection.Set` (other ABC imports too) is deprecated in recent Python versions. Under the best circumstances six should put this in a `moves` module, but alas. The best approach is probably providing a try-except-ImportError shim.

**Comment by techalchemy** [comment]
yeah I just added the move to Six no big deal

```python
six.add_move(six.MovedAttribute("Set", "collections", "collections.abc"))
from six.moves import Set
```
